# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d463defb55a58fba28bdf34504688de2e416d06d66b97c511e96f6738448bcabbd0a465a9945f18f713eb122d7f7fca6fd2fd6aafa1095244b73808816b1c3

test:
  secret_key_base: 7738515396ae5c8726ec3257cf23c4e5988c1cde03bbfb5e7be1eab752410e0082b512baab78a81d3f8bfcaa24341c90c034e5209e312a2ab4702423c28c4bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
